### ISSUE TITLE
Select component seem distorted and grow as the text grows

### ISSUE THREAD

**Issue by gbenga504** [gbenga504/music-port#46]
The select component is a bit distorted and grows as its content grows. 

<img width="266" alt="image" src="https://github.com/gbenga504/music-port/assets/12268442/47c58e78-7e78-4c4b-bbfa-fbed4ed066d2">

Expected behavior
===================
We want the Select component to take the size of its parent and its content should be displayed with an ellipsis if too long.

**Comment by conorvenus** [comment]
If you don't mind, can I give this one a go? Also, where can I find this "Youtube Music is good" box?😄

**Comment by deepak-sourcecode** [comment]
Hi @gbenga504, Is this issue still open? I'm just getting started with Open Source and found this on my issues page. Let me know if this open and the parent branch I should make my branch from. Thanks.

**Comment by gbenga504** [comment]
> Hi @gbenga504, Is this issue still open? I'm just getting started with Open Source and found this on my issues page. Let me know if this open and the parent branch I should make my branch from. Thanks.

Hi @deepak-sourcecode , this issue is no longer relevant. Still interested in looking at a couple of issues?
