### ISSUE TITLE
Error occurs when exporting to Youtube music

### ISSUE THREAD

**Issue by gbenga504** [gbenga504/music-port#51]
When converting a playlist to Youtube Music, an error occurs 

<img width="1440" alt="image" src="https://github.com/gbenga504/music-port/assets/12268442/fef0d816-72e1-4f32-ad99-3684545fa882">

<img width="1440" alt="image" src="https://github.com/gbenga504/music-port/assets/12268442/0634636a-ab7d-45e1-80de-e9dcb5a63f47">

**Comment by narhzih** [comment]
I would like to work on this

**Comment by gbenga504** [comment]
https://ytmusic-api.zectan.com/guides/getting-started.html

**Comment by gbenga504** [comment]
Fixed !
