### ISSUE TITLE
Make the Discover page mobile responsive

### ISSUE THREAD

**Issue by gbenga504** [gbenga504/music-port#93]
We want the Discover page, which is the homepage of our web app mobile responsive.  Please reach out to me if you have questions 

TODO
==========

- [ ] This page should be responsive on all mobile devices
- [ ] This page should be responsive on regular desktop screens
- [ ] This page should also be responsive and display properly on very large screens i.e monitors
- [ ] Please rely on tailwind's responsive classes as much as possible

N:B - **This does not include making the Player responsive**

**Comment by emmacode** [comment]
Working on this issue, please assign it to me
